### ISSUE TITLE
span removed after save

### ISSUE THREAD

**Issue by maximaexchen** [sebkln/linebreak#1] opened 2017-11-17 08:01 UTC
Hi.
 
installed and selectable in editor.
I can instert via Style-Selector but after I save the page it is removed.

I have added the code to TypoScript.

lib.parseFunc_RTE.allowTags := addToList(wbr)
lib.parseFunc_RTE.nonTypoTagStdWrap.HTMLparser.tags.span.fixAttrib.class.removeIfEquals = shy
lib.parseFunc_RTE.nonTypoTagStdWrap.HTMLparser.rmTagIfNoAttrib = span

If I select a whole word the span is not removed.

Any suggestions?

**Comment by sebkln** [comment] 2017-11-17 19:33
Thanks for your feedback! I can confirm that there currently is a bug when using the *Formatting Styles* selector to add the *span shy* style.

The reason is that this style is added by the YAML config line
```yaml
- { name: "span shy", element: "span", attributes: { 'class': 'shy' } }
```
which I needed to generally allow span elements with this class inside the RTE. But this line does also add this `<span class"shy"></span>` element to the selector.

- If you use the selector on a word, it is wrapped inside this element (but removed in the frontend by TypoScript).
- If you use the selector on the current cursor position, the element is added, but with no content (no `&shy;` entity) – and empty elements get removed on save.

Adding it to the selector was actually a side effect. It was not intended to use the selector to add the `&shy;` entity.

I will look into this issue. Either I'll try to remove the style from the selector and allow it through the plugin instead. Or maybe it is possible to insert the `&shy;` entity through the selector.

**Comment by sebkln** [comment] 2017-11-17 20:39
Okay, the quick solution is as following.
First, delete the following (last) line:
```yaml
editor:
  config:
    stylesSet:
      - { name: "span shy", element: "span", attributes: { 'class': 'shy' } }
```
This removes the span from the `Formatting Styles` selector. Now span elements are disallowed again.

Then add (or extend) this line:
```yaml
editor:
  config:
    extraAllowedContent: "*(*)[data-*]; span(shy)"
```
This allows span elements with the class 'shy' (as well as data attributes, which already were part of the TYPO3 base config).

Please test this and give me a short feedback. I will adapt the documentation accordingly. In a later step I'll try to allow this directly through the plugin.

**Comment by maximaexchen** [comment] 2017-11-17 20:50
What do you mean with "which already were part of the TYPO3 base config"?
I haven't found something about it. A link to the docu?
How could I insert a "shy" via the ckeditor now? In htmlarea times there was field under "scpecial chars"... 
Or did I miss something?

**Comment by sebkln** [comment] 2017-11-17 21:06
I was referring to the [TYPO3 default configuration of CKEditor](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/rte_ckeditor/Configuration/RTE/Editor/Base.yaml).

There already exists the following configuration:
```yaml
editor:
  config:
    extraAllowedContent: "*(*)[data-*]"
```

So, if you want to keep using data attributes in the RTE, you'll have to extend the line as shown above. Otherwise, just use the value `"span(shy)"`.

To use the `&shy;` entity and/or the `<wbr>` tag, you can add buttons to the RTE toolbar.

You can find the necessary configuration in the *[README.md](https://github.com/sebkln/linebreak/blob/master/README.md)* (`toolbarGroups` or `toolbar`, whichever you use to adapt your custom toolbar).

Edit: [Here is a complete configuration as an example.](https://gist.github.com/sebkln/116041fb6353c55bc29c8294591cab21)

**Comment by maximaexchen** [comment] 2017-11-17 21:27
Ok. I see. Thanks.
I don't get the buttons via 

toolbar:
  - [ 'ShyEntity', 'WbrTag' ]
or
toolbarGroups:
   - { name: linebreak }

I propably hava a configuration problem. somewhere else.
But the correct yaml file is used (verified by changing style names) ... strange.

But thank you anyway!

**Comment by sebkln** [comment] 2017-11-18 10:53
You're welcome!

If the buttons don't get displayed in the toolbar, please check if you correctly added the linebreak plugin to `externalPlugins` as well as `extraPlugins`. Maybe it's just an indentation issue.

As the original bug is patched, I'm closing this now.

**Closed as completed by sebkln** 2017-11-18 10:53 UTC
Labels: bug, Needs feedback from author
